org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.218
loader_version_range=[1,)

mod_id=path_lighter_drone
mod_name=Assistance Drone Path Lighter Addon
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.uemc.path_lighter_drone
mod_authors=aperez26323
mod_description=Adds path-lighting support to Assistance Drone follow mode.
